/* SomnGuard Admin — §7 Monitoreo · §8 Analítica · §9 Auditoría/Observabilidad/Settings */
'use strict';
(function () {
  var V = window.SG_VIEWS, H = window.SGV;

  /* ================= §7 NOTIFICATIONS ================= */
  V.notifications = function () {
    var S = SG_SEED, st = SG.state;
    var list = S.NOTIFICATIONS.filter(function (n) {
      if (st.notStatus && n.status !== st.notStatus) return false;
      var q = (st.notQ || '').toLowerCase();
      if (q && (n.title + ' ' + n.user + ' ' + n.message).toLowerCase().indexOf(q) < 0) return false;
      return true;
    });
    var fails = S.NOTIFICATIONS.filter(function (n) { return n.status === 'NOTIFICATION_FAILED'; }).length;
    return SG.page('Notificaciones', 'Notificaciones', 'Avisos enviados a los conductores. ' + SG.permChip('notification.read (+ send propuesto)'),
      '<button class="btn btn-secondary btn-sm" onclick="SG.exportCSV(\'notifications.csv\',SG_SEED.NOTIFICATIONS)">Export CSV</button><button class="btn btn-primary btn-sm" onclick="SGV.notSend()">+ Envío manual (propuesto)</button>',
      SG.tech('Ficha técnica', 'Se crean solas ante eventos critical (EV-SOM-05, EV-DIS-02/04, EV-CIN-01/02) al propietario del equipo · reintentos máx 3 con backoff.') +
      SG.strip('📬 entrega <b>80%</b> · 👀 lectura <b>50%</b> · 🔴 <b>1</b> FAILED · ⏳ <b>1</b> en cola') +
      '<form class="card filters" onsubmit="return false" style="grid-template-columns:1fr 1fr 1fr auto"><div class="form-field"><label>status (5)</label><select onchange="SG.state.notStatus=this.value;SG.render()"><option value="">Todos</option>' + ['NOTIFICATION_PENDING', 'NOTIFICATION_SENT', 'NOTIFICATION_DELIVERED', 'NOTIFICATION_READ', 'NOTIFICATION_FAILED'].map(function (o) { return '<option ' + (st.notStatus === o ? 'selected' : '') + '>' + o + '</option>'; }).join('') + '</select></div>' +
      '<div class="form-field"><label>channel push/email/in_app</label><select onchange="SG.toast(\'Filtro channel (sim.)\')"><option>Todos</option><option>push</option><option>email</option><option>in_app</option></select></div>' +
      '<div class="form-field"><label>Buscar (retry&gt;0 · con error · alert_id)</label><div class="search-input"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"></circle><path d="m20 20-3.5-3.5"></path></svg><input type="search" value="' + SG.esc(st.notQ) + '" oninput="SG.state.notQ=this.value;SG.render()" /></div></div>' +
      '<button class="btn btn-secondary" onclick="SG.state.notQ=\'\';SG.state.notStatus=\'\';SG.render()">Limpiar</button></form>' +
      '<div class="panel"><div class="data-table-wrap"><table class="data-table"><thead><tr><th>user</th><th>alert/event</th><th>title</th><th>channel</th><th>status</th><th>timeline</th><th>retry</th><th>error</th><th></th></tr></thead><tbody>' +
      list.map(function (n) { return '<tr><td><strong>' + n.user + '</strong></td><td><a href="#/admin/events/' + n.event + '"><code>' + n.event.slice(0, 8) + '…</code></a></td><td><strong>' + SG.esc(n.title) + '</strong><div style="font-size:11px;color:var(--text-muted)">' + SG.esc(SG.trunc(n.message, 60)) + '</div></td><td><code>' + n.channel + '</code></td><td>' + SG.notBadge(n.status) + '</td><td style="font-size:11.5px">sent ' + SG.fmtDT(n.sent_at) + '<br/>del ' + SG.fmtDT(n.delivered_at) + '<br/>read ' + SG.fmtDT(n.read_at) + '</td><td>' + n.retry + '/3' + (n.retry ? ' 🔴' : '') + '</td><td style="color:#ffa9b3">' + SG.esc(n.error || '—') + '</td><td><div style="display:flex;gap:6px"><button class="btn btn-secondary btn-sm" onclick="SGV.notDetail(\'' + n.id + '\')">Ver</button><button class="btn btn-secondary btn-sm" onclick="SG.toast(\'Reintento retry++ max3 exponencial (sim.)\')">Reintentar</button></div></td></tr>'; }).join('') + '</tbody></table></div></div>' +
      '<div class="panel" style="margin-top:14px"><div class="panel-header"><div><h2 class="panel-title">Plantillas por event_type+severity (Should · admin gestiona)</h2><p class="panel-subtitle">Sección propuesta — no en DB aún</p></div><span class="chip">TODO</span></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>evento</th><th>título</th><th>channel</th></tr></thead><tbody>' + S.NOTIF_TEMPLATES.map(function (t) { return '<tr><td><code>' + t.event + '</code></td><td>' + SG.esc(t.title) + '</td><td>' + t.channel + '</td></tr>'; }).join('') + '</tbody></table></div></div>');
  };
  H.notDetail = function (id) {
    var n = SG_SEED.NOTIFICATIONS.filter(function (x) { return x.id === id; })[0]; if (!n) return;
    SG.openDrawer('<button class="btn btn-ghost btn-sm" onclick="SG.closeDrawer()">✕ Cerrar</button><h2>' + SG.esc(n.title) + '</h2><p>' + SG.notBadge(n.status) + ' <code>' + n.channel + '</code></p>' +
      '<div class="stepper"><span class="step ' + (n.sent_at ? 'done' : '') + '">SENT</span><span class="step-arrow">→</span><span class="step ' + (n.delivered_at ? 'done' : '') + '">DELIVERED</span><span class="step-arrow">→</span><span class="step ' + (n.read_at ? 'done' : '') + '">READ</span></div>' +
      '<dl class="detail-grid"><div class="detail-item"><dt>user</dt><dd>' + n.user + '</dd></div><div class="detail-item"><dt>retry_count</dt><dd>' + n.retry + '/3</dd></div><div class="detail-item"><dt>error_message</dt><dd>' + SG.esc(n.error || '—') + '</dd></div><div class="detail-item"><dt>message</dt><dd>' + SG.esc(n.message) + '</dd></div></dl>' +
      '<div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn btn-secondary btn-sm" onclick="SG.toast(\'Reenviado cambiando channel (sim.)\')">Reenviar (otro channel)</button><button class="btn btn-secondary btn-sm" onclick="SG.closeDrawer();SG.toast(\'Marcada leída override (sim.)\')">Marcar leída</button></div>');
  };
  H.notSend = function () { SG.openModal('<header class="modal-header"><h2>Envío manual · notification.send (propuesto)</h2><button class="icon-btn" onclick="SG.closeModal()">✕</button></header><div class="modal-body"><div class="form-field"><label>user*</label><select><option>laura.pineda@somnguard.com</option><option>andres.rios@somnguard.com</option></select></div><div class="form-field"><label>title*</label><input placeholder="Prueba operativa" /></div><div class="form-field"><label>message*</label><textarea></textarea></div><div class="form-field"><label>channel*</label><select><option>push</option><option>email</option><option>in_app</option></select></div></div><footer class="modal-footer"><button class="btn btn-secondary" onclick="SG.closeModal()">Cancelar</button><button class="btn btn-primary" onclick="SG.closeModal();SG.toast(\'Notificación encolada PENDING (sim.)\')">Enviar</button></footer>'); };

  /* ================= §8 ANALYTICS ================= */
  V.timeline = function () {
    var S = SG_SEED;
    return SG.page('Analytics', 'Timeline analítica (MV)', 'Eventos ya cruzados con catálogos. ' + SG.permChip('analytics.read'),
      '<button class="btn btn-secondary btn-sm" onclick="SG.refreshMVs()">⟳ Refresh MVs</button><button class="btn btn-secondary btn-sm" onclick="SG.exportCSV(\'timeline.csv\',SG_SEED.EVENTS)">Export CSV</button>',
      SG.tech('Ficha técnica', '<code>analytics.v_event_timeline</code> · 1 fila por evento vigente · columnas: event_id, device+serial, type, categoría, severidad, occurred_at, offline, status, evidencia · refresh ' + SG.ago(SG.state.mvLast) + '.') +
      '<div class="panel"><div class="data-table-wrap"><table class="data-table"><thead><tr><th>occurred_at</th><th>event_id</th><th>device/serial</th><th>type code/name</th><th>cat</th><th>sev/prio</th><th>offline</th><th>status</th><th>evidencia</th></tr></thead><tbody>' +
      S.EVENTS.map(function (e) { var ev = S.EVIDENCES.filter(function (x) { return x.event === e.id; })[0]; return '<tr><td>' + SG.fmtDT(e.occurred_at) + '</td><td><a href="#/admin/events/' + e.id + '"><code>' + e.id.slice(0, 8) + '…</code></a></td><td><code>' + e.serial + '</code></td><td><code>' + e.type + '</code> ' + SG.esc(e.type_name) + '</td><td>' + SG.catChip(e.category) + '</td><td>' + SG.sevBadge(e.severity) + '</td><td>' + (e.offline ? 'sí' : 'no') + '</td><td>' + SG.evBadge(e.status) + '</td><td>' + (ev ? '<code>' + ev.media + '</code>' : 'NULL') + '</td></tr>'; }).join('') + '</tbody></table></div></div>');
  };
  V.metrics = function () {
    var S = SG_SEED;
    var tot = S.METRICS_DAILY.reduce(function (a, m) { return a + m.total; }, 0);
    var crit = S.METRICS_DAILY.reduce(function (a, m) { return a + m.critical; }, 0);
    var high = S.METRICS_DAILY.reduce(function (a, m) { return a + m.high; }, 0);
    return SG.page('Analytics', 'Métricas diarias (MV)', 'Agregados por día (Bogotá), equipo y severidad. ' + SG.permChip('analytics.read'),
      '<button class="btn btn-secondary btn-sm" onclick="SG.toast(\'Export PNG (sim.)\')">Export PNG</button><button class="btn btn-secondary btn-sm" onclick="SG.exportCSV(\'metrics.csv\',SG_SEED.METRICS_DAILY)">Export CSV</button>',
      SG.tech('Ficha técnica', '<code>analytics.v_metrics_daily</code> · filtros: rango 7/30/90d, device, user, tipo, categoría, severidad · p95 &lt;500ms @10k.') +
      '<div class="kpi-grid" style="grid-template-columns:repeat(5,minmax(0,1fr))">' + [['event_count total', tot], ['critical_count', crit], ['high_count', high], ['promedio/día', (tot / 7).toFixed(1)], ['día pico', '09-08 (31)']].map(function (k) { return '<div class="kpi-card"><h4>' + k[0] + '</h4><div class="kpi-val">' + k[1] + '</div></div>'; }).join('') + '</div>' +
      '<div class="charts-grid"><div class="chart-card"><h3>Barras apiladas día × severity</h3><p>Por día y severidad</p><div class="bars">' + S.METRICS_DAILY.map(function (m) { return '<div class="bar"><div class="seg" style="height:' + m.critical / 32 * 100 + '%;background:#ef5a6c"></div><div class="seg" style="height:' + m.high / 32 * 100 + '%;background:#f2a154"></div><div class="seg" style="height:' + (m.total - m.critical - m.high) / 32 * 100 + '%;background:rgba(0,200,200,.55)"></div><b>' + m.date.slice(5) + '</b></div>'; }).join('') + '</div></div>' +
      '<div class="chart-card"><h3>Ranking device/user</h3><p>event/critical por asignación vigente</p><div class="donut-row"><span style="min-width:130px">SG-2026-0001</span><span class="track"><i style="width:80%;background:#ef5a6c"></i></span><b>5/1</b></div><div class="donut-row"><span style="min-width:130px">SG-2026-0002</span><span class="track"><i style="width:55%;background:#f2a154"></i></span><b>4/0</b></div><div class="donut-row"><span style="min-width:130px">SG-2026-0003</span><span class="track"><i style="width:40%;background:#6c90f0"></i></span><b>3/0</b></div><h3 style="margin-top:10px">Heatmap category × severity</h3><p>SOMNOLENCE×critical · DISTRACTION×high concentran riesgo nocturno</p></div></div>');
  };
  V.reports = function () {
    if (!SG.can('analytics.report') && SG.state.role !== 'admin') return SG.guardBlock('analytics.report');
    var S = SG_SEED;
    return SG.page('Reportes', 'Reportes + Resumen IA', 'PDFs con métricas, IA y evidencias. ' + SG.permChip('analytics.report'),
      '<button class="btn btn-secondary" onclick="SGV.aiSummary()">✨ Resumen IA</button><button class="btn btn-primary" onclick="SGV.repCreate()">+ Nuevo reporte PDF/HTML</button>',
      SG.tech('Ficha técnica', 'Resumen IA: modelo por definir (Q-015), caché 1h por usuario+periodo · reportes async (<code>202 Accepted</code>) con descarga · la app offline muestra caché · video WebRTC a demanda: <b>POST-MVP</b>.') +
      '<div class="panel"><div class="data-table-wrap"><table class="data-table"><thead><tr><th>id</th><th>título</th><th>periodo</th><th>estado</th><th>by</th><th>created</th><th>tamaño</th><th></th></tr></thead><tbody>' +
      S.REPORTS.map(function (r) { return '<tr><td><code>' + r.id + '</code></td><td><strong>' + SG.esc(r.title) + '</strong></td><td>' + r.period + '</td><td>' + (r.status === 'Listo' ? '<span class="status-badge status-success">● Listo</span>' : '<span class="status-badge status-warning">● Generando</span>') + '</td><td>' + r.by + '</td><td>' + SG.fmtDT(r.created_at) + '</td><td>' + r.size + '</td><td><div style="display:flex;gap:6px">' + (r.status === 'Listo' ? '<button class="btn btn-secondary btn-sm" onclick="SG.toast(\'Descarga attachment/inline (sim.)\')">Descargar</button>' : '<span class="chip">202 Accepted…</span>') + '<button class="btn btn-danger-subtle btn-sm" onclick="SG.toast(\'Reporte eliminado (sim.)\')">Eliminar</button></div></td></tr>'; }).join('') + '</tbody></table></div></div>');
  };
  H.aiSummary = function () {
    SG.openModal('<header class="modal-header"><h2>Resumen IA · POST /analytics/summary</h2><button class="icon-btn" onclick="SG.closeModal()">✕</button></header><div class="modal-body"><div class="form-field"><label>periodo</label><select><option>7d</option><option>30d</option><option>90d</option></select></div><div class="form-field"><label>device/user (opcional)</label><input placeholder="SG-2026-0001 / laura@…" /></div><button class="btn btn-primary" onclick="document.getElementById(\'aiOut\').style.display=\'block\';SG.toast(\'LLM generado + cache 1h user+periodo (sim.)\')">Generar</button><div id="aiOut" style="display:none;margin-top:12px"><div class="alert alert-success"><b>Patrones:</b> microsueños 02:00-03:00 en SG-2026-0001 (2 críticas) · <b>Tendencia:</b> distracción alta +40% 7d · <b>Conclusión:</b> reforzar descanso nocturno y bloqueo de teléfono.</div><div style="display:flex;gap:8px"><button class="btn btn-secondary btn-sm" onclick="SG.copyTxt(\'Resumen IA SomnGuard 7d\')">Copiar</button><button class="btn btn-secondary btn-sm" onclick="SG.toast(\'Regenerado (sim.)\')">Regenerar</button><button class="btn btn-secondary btn-sm" onclick="SG.toast(\'Incluido en reporte (sim.)\')">Incluir en reporte</button></div></div></div>');
  };
  H.repCreate = function () { SG.openModal('<header class="modal-header"><h2>Nuevo reporte · POST /reports (async)</h2><button class="icon-btn" onclick="SG.closeModal()">✕</button></header><div class="modal-body"><div class="form-field"><label>título*</label><input value="Riesgo flota 7d" /></div><div class="form-field"><label>periodo*</label><input value="2026-09-02..2026-09-09" /></div><div class="form-field"><label>devices</label><input placeholder="todos / SG-2026-0001" /></div><label style="font-size:13px"><input type="checkbox" checked /> timeline + métricas + IA + thumbnails evidencia</label><div class="form-field"><label>formato</label><select><option>PDF</option><option>HTML</option></select></div></div><footer class="modal-footer"><button class="btn btn-secondary" onclick="SG.closeModal()">Cancelar</button><button class="btn btn-primary" onclick="SG.closeModal();SG.toast(\'Reporte encolado 202 Accepted (sim.)\')">Generar</button></footer>'); };

  /* ================= §9 AUDIT / OBSERVABILITY / SETTINGS ================= */
  V.audit = function () {
    var S = SG_SEED, t = SG.state.auditTab;
    var tabs = [['logins', 'Logins'], ['users', 'Usuarios'], ['devices', 'Devices'], ['events', 'Eventos'], ['configs', 'Configs'], ['notifications', 'Notifs'], ['provisioning', 'Provisioning'], ['versions', 'Versiones config']];
    var body = '';
    if (t === 'logins') body = '<div class="data-table-wrap"><table class="data-table"><thead><tr><th>attempted_at</th><th>email</th><th>outcome</th><th>IP</th></tr></thead><tbody>' + S.AUDIT_LOGIN.slice(0, 6).map(function (a) { return '<tr><td>' + SG.fmtDT(a.attempted_at) + '</td><td>' + SG.esc(a.email_attempted) + '</td><td>' + SG.outcomeBadge(a.outcome) + '</td><td><code>' + a.ip + '</code></td></tr>'; }).join('') + '</tbody></table></div>';
    else if (t === 'versions') body = '<div class="timeline">' + S.CONFIG_HISTORY.map(function (h) { return '<div class="timeline-item"><time>' + SG.fmtDT(h.created_at) + '</time><span><code>' + h.serial + ' v' + h.version + '</code> snapshot JSONB · ' + SG.esc(h.changed_by) + ' · <i>' + SG.esc(h.change_reason) + '</i> [diff/rollback]</span></div>'; }).join('') + '</div>';
    else if (t === 'provisioning') body = '<div class="data-table-wrap"><table class="data-table"><thead><tr><th>fecha</th><th>token</th><th>action</th><th>actor</th></tr></thead><tbody>' + S.PROV_AUDIT.map(function (a) { return '<tr><td>' + SG.fmtDT(a.created_at) + '</td><td><code>' + a.token + '</code></td><td>' + a.action + '</td><td>' + SG.esc(a.actor || 'device') + '</td></tr>'; }).join('') + '</tbody></table></div>';
    else {
      var ent = t;
      body = '<div class="timeline">' + S.STATUS_AUDIT.filter(function (a) { return a.entity === ent || (t === 'notifications' && a.entity === 'notification') || (t === 'configs' && a.entity === 'config'); }).map(function (a) { return '<div class="timeline-item"><time>' + SG.fmtDT(a.at) + '</time><span><code>' + (a.ref || '') + '</code> <code>' + a.from + '</code> → <code>' + a.to + '</code> · ' + SG.esc(a.by) + ' · <i>' + SG.esc(a.reason) + '</i> <a href="javascript:SG.toast(\'Ver objeto (sim.)\')">Ver objeto</a></span></div>'; }).join('') + '</div>';
    }
    return SG.page('Auditoría', 'Auditoría global (8 tabs)', 'Quién cambió qué y cuándo (solo lectura). ' + SG.permChip('audit.read'),
      '<button class="btn btn-secondary btn-sm" onclick="SG.exportCSV(\'audit.csv\',SG_SEED.STATUS_AUDIT)">Export CSV</button>',
      SG.tech('Ficha técnica', 'Esquema por entidad: <code>from</code> → <code>to</code> + actor + fecha + motivo · <code>from</code> NULL = creación · sin edición · transversal: <code>created_by/at, version, is_active</code> · soft-delete, nunca DELETE físico.') +
      '<section class="panel"><div class="tabs">' + tabs.map(function (x) { return '<button class="tab ' + (t === x[0] ? 'active' : '') + '" onclick="SG.state.auditTab=\'' + x[0] + '\';SG.render()">' + x[1] + '</button>'; }).join('') + '</div><div class="panel-body"><form class="card filters" onsubmit="return false" style="grid-template-columns:1fr 1fr 1fr auto"><div class="form-field"><label>entidad_id / actor</label><input placeholder="uuid / email" /></div><div class="form-field"><label>to_status / action</label><input placeholder="DEVICE_SUSPENDED / USED" /></div><div class="form-field"><label>rango fecha</label><input type="date" /></div><button class="btn btn-secondary" onclick="SG.toast(\'Filtros aplicados (sim.)\')">Filtrar</button></form>' + (body || '<p style="color:var(--text-muted)">Sin registros en esta pestaña (mock).</p>') + '</div></section>');
  };

  V.observability = function () {
    return SG.page('Observabilidad', 'Observabilidad técnica (Admin ops)', 'Salud de la plataforma y diagnóstico. ' + SG.permChip('audit.read'),
      '<a class="btn btn-secondary btn-sm" href="javascript:SG.toast(\'Grafana embed (sim.)\')">Abrir Grafana</a>',
      SG.tech('Ficha técnica', 'ADR-007 OTel+LGTM · logs JSON sin PII/secrets · <code>trace_id</code> + <code>X-Request-ID</code> · sampling 10% (100% errores) · <code>/actuator/prometheus</code>.') +
      '<div class="kpi-grid" style="grid-template-columns:repeat(4,minmax(0,1fr))">' + [['API p95', '180ms 🟢'], ['ingesta ev/s', '0.02 🟢'], ['MinIO lat', '45ms 🟢'], ['FAILED notif', '20% 🔴']].map(function (k) { return '<div class="kpi-card"><h4>' + k[0] + '</h4><div class="kpi-val" style="font-size:20px">' + k[1] + '</div></div>'; }).join('') + '</div>' +
      '<div class="charts-grid"><div class="chart-card"><h3>Health</h3><p>GET /health {ok} · /health/ready {BD+MinIO} · /health/live · pg_isready · /actuator/health/info</p><p>🟢 API · 🟢 PostgreSQL 16 · 🟢 MinIO somnguard-evidence · 🟢 pg_cron</p><h3>Logs (JSON Lines)</h3><pre class="code-view">{"ts":"2026-09-09T02:11:05Z","level":"info","service":"api","module":"telemetry","trace_id":"a1b2…b5c6","device_id":"d-001","event":"event.ingested"}\n{"ts":"2026-09-09T02:11:06Z","level":"error","service":"api","module":"monitoring","trace_id":"a1b2…b5c6","event":"notif.failed","retry":3}</pre></div>' +
      '<div class="chart-card"><h3>Dashboards Grafana (links)</h3><p>API Global (RED, JVM heap/GC/threads, DB/Redis pool) · Auth (success/failed, refresh, 401/403) · Telemetry (ingested/s, batch, MinIO, duplicados) · Device Sync (online/offline, buffer age, config pull) · Monitoring (sent/delivered/failed, retry queue) · Analytics (p50/p95, report time, AI tokens)</p><h3>Alertas referencia</h3><p>PG caído P0 · disco&gt;85% P1 · migración falla P1 · 5xx alta P1 · p95&gt;SLO P2 → Alertmanager APIHighErrorRate, DeviceOffline</p><h3>Incidentes P0-P3</h3><p>IC/técnico/comms · detección→triaje→contención→diagnóstico→mitigación→postmortem blameless P0/P1</p><h3>Backups</h3><p>pg_dump granular + PITR prod (RTO/RPO Q-017) · restore drill + liquibase status · dumps PII cifrados, no git</p></div></div>' +
      '<div class="alert alert-info">SLO chips (NFR): alerta local &lt;1s · &lt;2s/frame · arranque &lt;60s · &lt;10k users escalable · ≥99% mensual.</div>');
  };

  V.settings = function () {
    return SG.page('Settings', 'Settings (propuesto)', 'Límites y retenciones (solo lectura). ' + SG.permChip('catalog.read'),
      '', '<div class="panel"><div class="data-table-wrap"><table class="data-table"><thead><tr><th>clave</th><th>valor vigente</th><th>propuesta</th></tr></thead><tbody>' +
      [['audit_login.retention', '2 años (job mensual)', '—'], ['evidence.retention', '90d normal / 5a critical (ILM)', '—'], ['config_history.retention', '3 años', '—'], ['alert_log.retention', '5 años', '—'], ['auth.login.rate', '5 req/min/IP → 429 Retry-After:60', 'captcha opcional'], ['auth.lockout', '5 fallos → locked 15min', '—'], ['MFA Admin', 'no existe (0 resultados) → propuesta TOTP/WebAuthn', 'TODO']].map(function (r) { return '<tr><td><code>' + r[0] + '</code></td><td>' + r[1] + '</td><td>' + r[2] + '</td></tr>'; }).join('') + '</tbody></table></div><div class="table-footer"><span>Seguridad transversal: TLS1.2+, CORS portal/app, CSP, HSTS, secrets Vault/Sealed Secrets, OWASP mensual, logs sin PII/tokens/keys · Amenazas T-001..T-012 mitigadas · Mejora futura: MFA TOTP/WebAuthn Admin.</span></div></div>');
  };
})();
